apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring
  name: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - image: quay.io/sachinayyar/tekton-argocd:latest
          imagePullPolicy: Always
          name: spring
          ports:
            - containerPort: 8080
              protocol: TCP
           
