apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:e7463b1cb6957ba4c3efdbfb34c08fb7c9229913ef9c74d7f4db3d063c479163
  name: quay.io/sachinayyar/tekton-serverless
  newName: quay.io/sachinayyar/tekton-serverless
