apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
- namespace.yaml
images:
- digest: sha256:b272d8529f0e7cee1ae518b152ecfd9b16ef07a869ba245b186790ca40209ce9
  name: quay.io/sachinayyar/tekton-argocd
  newName: quay.io/sachinayyar/tekton-argocd:latest
