apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
images:
- digest: sha256:a5b59c0a5e6abc069684a71c737f7e0fc1a50452f12b1f243effff446abb729e
  name: quay.io/sachinayyar/tekton-serverless
  newName: quay.io/sachinayyar/tekton-serverless:c57fa68b2b4d0843309fd283549528199927c96f
