apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
- namespace.yaml
images:
- digest: sha256:36061f9d1cc61ce8cb5046e00203950390ecf153e0c51c37ed15755ddd084188
  name: quay.io/sachinayyar/tekton-argocd
  newName: quay.io/sachinayyar/tekton-argocd:latest
