apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
- namespace.yaml
images:
- digest: sha256:480b2933eee9f8f1d3b9a082582ee8479047304a4b7e1ef88787c5ae1e917568
  name: quay.io/sachinayyar/tekton-argocd
  newName: quay.io/sachinayyar/tekton-argocd:latest
