apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
- namespace.yaml
images:
- digest: sha256:e93e4baeefe818ebeb95f8d91ea1f0e65e06ff5417a9c2a31905435ad08fb83b
  name: quay.io/sachinayyar/tekton-argocd
  newName: quay.io/sachinayyar/tekton-argocd:latest
