apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- service.yaml
- namespace.yaml
images:
- digest: sha256:a8d9c24778c70b59c28bcf4a40c26eed45a6d5718903c34c7c121c8ca47939b4
  name: quay.io/sachinayyar/tekton-argocd
  newName: quay.io/sachinayyar/tekton-argocd:latest
